spring.thymeleaf.prefix: classpath:/templates/flat/

jdbc:
  driver: com.mysql.jdbc.Driver

spring:
  profiles:
    active: dev
    
---

spring:
  profiles: dev
jdbc:
  url: jdbc:mysql://localhost:3306/jg_lottery
  username: root
  password: